# Generated by Django 3.0.4 on 2020-03-12 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('moduleID',)},
            },
        ),
        migrations.CreateModel(
            name='ModuleYearSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleYear', models.CharField(max_length=4)),
                ('moduleSemester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.ModuleCode')),
            ],
            options={
                'unique_together': {('moduleID', 'moduleYear', 'moduleSemester')},
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('profID', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RateProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('moduleInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.ModuleYearSemester')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.Professors')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profTitle', models.CharField(max_length=30)),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.Professors')),
            ],
            options={
                'unique_together': {('profID', 'profTitle')},
            },
        ),
        migrations.CreateModel(
            name='ModulesTaughtBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.ModuleYearSemester')),
                ('moduleProfessors', models.ManyToManyField(to='Professors.ProfessorTitle')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professors.ModuleCode')),
            ],
            options={
                'unique_together': {('moduleID', 'moduleName')},
            },
        ),
    ]
